services:
  # Serviço do MongoDB
  mongo:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  # Serviço do Redis
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - app-network

  # Serviço da aplicação Node.js com nodemon
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./src:/usr/src/app/src
      - /usr/src/app/node_modules
    depends_on:
      - mongo
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
